package spring.learning.session7.stream_api;


import java.util.ArrayList;
import java.util.List;

public class MockSongs {
    public static List<String> getSongStrings() {
        List<String> songs = new ArrayList<>();

        songs.add("Pink Moon/Nick Drake");
        songs.add("Somersault/Zero 7");
        songs.add("Shiva Moon/Prem Joshua");
        songs.add("Circles/BT");
        songs.add("Deep Channel/Afro Celts");
        songs.add("Passenger/Headmix");
        songs.add("Listen/Tahiti 80");
        songs.add("Broken/Lovely Teardrops");
        songs.add("Stargazer/The Tea Party");
        songs.add("Velvet Sun/The Verve");
        songs.add("Falling Away/Deepsky");
        songs.add("Northern Crown/Moby");
        songs.add("Coming Home/Daft Punk");
        songs.add("Take Me With You/Massive Attack");
        songs.add("Desert Rose/Sting");
        songs.add("Dreams/Fleetwood Mac");
        songs.add("Waterloo Sunset/The Kinks");
        songs.add("Sultans Of Swing/Dire Straits");
        songs.add("Rebel Rebel/David Bowie");
        songs.add("Love Will Tear Us Apart/Joy Division");
        songs.add("Welcome To The Jungle/Guns N' Roses");
        songs.add("Sweet Child O' Mine/Guns N' Roses");
        songs.add("Purple Haze/Jimi Hendrix");
        songs.add("Smells Like Teen Spirit/Nirvana");
        songs.add("Stairway To Heaven/Led Zeppelin");
        songs.add("Imagine/John Lennon");
        songs.add("Like A Rolling Stone/Bob Dylan");
        songs.add("Born To Run/Bruce Springsteen");
        songs.add("No Woman No Cry/Bob Marley");
        songs.add("California Love/2Pac");
        songs.add("Billie Jean/Michael Jackson");
        songs.add("Bohemian Rhapsody/Queen");
        songs.add("Sweet Dreams/Eurythmics");
        songs.add("Creep/Radiohead");
        songs.add("Killing Me Softly/The Fugees");
        songs.add("Dancing Queen/ABBA");
        songs.add("Hallelujah/Jeff Buckley");
        songs.add("God Only Knows/The Beach Boys");
        songs.add("Gimme Shelter/The Rolling Stones");
        songs.add("Hey Jude/The Beatles");
        songs.add("London Calling/The Clash");
        songs.add("Karma Police/Radiohead");
        songs.add("The Message/Grandmaster Flash");
        songs.add("With Or Without You/U2");
        songs.add("One/U2");
        songs.add("Nothing Else Matters/Metallica");
        songs.add("Enter Sandman/Metallica");
        songs.add("November Rain/Guns N' Roses");
        songs.add("Lose Yourself/Eminem");
        songs.add("Wonderwall/Oasis");
        songs.add("Yesterday/The Beatles");
        songs.add("Come As You Are/Nirvana");
        songs.add("Paranoid/Black Sabbath");
        songs.add("Walk This Way/Aerosmith");
        songs.add("Redemption Song/Bob Marley");
        songs.add("Go Your Own Way/Fleetwood Mac");
        songs.add("The Unforgiven/Metallica");
        songs.add("Under The Bridge/Red Hot Chili Peppers");
        songs.add("Comfortably Numb/Pink Floyd");
        songs.add("Wish You Were Here/Pink Floyd");
        songs.add("Sweet Home Alabama/Lynyrd Skynyrd");
        songs.add("Freebird/Lynyrd Skynyrd");
        songs.add("Another Brick In The Wall/Pink Floyd");
        songs.add("Sympathy For The Devil/The Rolling Stones");
        songs.add("Paint It Black/The Rolling Stones");
        songs.add("Start Me Up/The Rolling Stones");
        songs.add("Superstition/Stevie Wonder");
        songs.add("Dancing In The Dark/Bruce Springsteen");
        songs.add("Where The Streets Have No Name/U2");
        songs.add("Pride/U2");
        songs.add("Hotel California/Eagles");
        songs.add("Roxanne/The Police");
        songs.add("Every Breath You Take/The Police");
        songs.add("Message In A Bottle/The Police");
        songs.add("Smoke On The Water/Deep Purple");
        songs.add("Sweet Emotion/Aerosmith");
        songs.add("Dream On/Aerosmith");
        songs.add("Back In Black/AC/DC");
        songs.add("Highway To Hell/AC/DC");
        songs.add("Thunderstruck/AC/DC");
        songs.add("Livin' On A Prayer/Bon Jovi");
        songs.add("Don't Stop Believin'/Journey");
        songs.add("Sweet Caroline/Neil Diamond");
        songs.add("Piano Man/Billy Joel");
        songs.add("Uptown Girl/Billy Joel");
        songs.add("Take On Me/A-ha");
        songs.add("Careless Whisper/George Michael");
        songs.add("Faith/George Michael");
        songs.add("Zombie/The Cranberries");
        songs.add("Bitter Sweet Symphony/The Verve");
        songs.add("Yellow/Coldplay");
        songs.add("Fix You/Coldplay");
        songs.add("Viva La Vida/Coldplay");
        songs.add("Mr. Brightside/The Killers");
        songs.add("Californication/Red Hot Chili Peppers");
        songs.add("Seven Nation Army/The White Stripes");
        songs.add("Crazy/Gnarls Barkley");
        songs.add("99 Problems/Jay-Z");
        songs.add("Stronger/Kanye West");
        songs.add("Empire State of Mind/Jay-Z feat. Alicia Keys");
        songs.add("Toxic/Britney Spears");
        songs.add("...Baby One More Time/Britney Spears");
        songs.add("Umbrella/Rihanna");
        songs.add("Crazy in Love/Beyoncé feat. Jay-Z");
        songs.add("Single Ladies/Beyoncé");
        songs.add("Hey Ya!/OutKast");
        songs.add("Ms. Jackson/OutKast");
        songs.add("In Da Club/50 Cent");
        songs.add("Paper Planes/M.I.A.");
        songs.add("Rehab/Amy Winehouse");
        songs.add("Valerie/Amy Winehouse");
        songs.add("Rolling in the Deep/Adele");
        songs.add("Someone Like You/Adele");
        songs.add("Hello/Adele");
        songs.add("Uptown Funk/Mark Ronson feat. Bruno Mars");
        songs.add("Get Lucky/Daft Punk feat. Pharrell Williams");
        songs.add("Happy/Pharrell Williams");
        songs.add("Royals/Lorde");
        songs.add("Shake It Off/Taylor Swift");
        songs.add("Bad Blood/Taylor Swift");
        songs.add("Blank Space/Taylor Swift");
        songs.add("Thinking Out Loud/Ed Sheeran");
        songs.add("Shape of You/Ed Sheeran");
        songs.add("Blurred Lines/Robin Thicke feat. T.I. & Pharrell");
        songs.add("Can't Feel My Face/The Weeknd");
        songs.add("Starboy/The Weeknd feat. Daft Punk");
        songs.add("Hotline Bling/Drake");
        songs.add("God's Plan/Drake");
        songs.add("Sicko Mode/Travis Scott");
        songs.add("Humble/Kendrick Lamar");
        songs.add("Alright/Kendrick Lamar");
        songs.add("Bad Guy/Billie Eilish");
        songs.add("When the Party's Over/Billie Eilish");
        songs.add("Old Town Road/Lil Nas X");
        songs.add("Shallow/Lady Gaga & Bradley Cooper");
        songs.add("Bad Romance/Lady Gaga");
        songs.add("Poker Face/Lady Gaga");
        songs.add("Just Dance/Lady Gaga");
        songs.add("Wrecking Ball/Miley Cyrus");
        songs.add("Party In The U.S.A./Miley Cyrus");
        songs.add("Firework/Katy Perry");
        songs.add("Roar/Katy Perry");
        songs.add("Dark Horse/Katy Perry");
        songs.add("Teenage Dream/Katy Perry");
        songs.add("Call Me Maybe/Carly Rae Jepsen");
        songs.add("We Can't Stop/Miley Cyrus");
        songs.add("Chandelier/Sia");
        songs.add("Elastic Heart/Sia");
        songs.add("Cheap Thrills/Sia");
        songs.add("Let It Go/Idina Menzel");
        songs.add("Happy/Pharrell Williams");
        songs.add("All About That Bass/Meghan Trainor");
        songs.add("Despacito/Luis Fonsi & Daddy Yankee feat. Justin Bieber");
        songs.add("Sorry/Justin Bieber");
        songs.add("Love Yourself/Justin Bieber");
        songs.add("What Do You Mean?/Justin Bieber");
        songs.add("Havana/Camila Cabello feat. Young Thug");
        songs.add("Señorita/Shawn Mendes & Camila Cabello");
        songs.add("Stitches/Shawn Mendes");
        songs.add("Treat You Better/Shawn Mendes");
        songs.add("Closer/The Chainsmokers feat. Halsey");
        songs.add("Don't Let Me Down/The Chainsmokers feat. Daya");
        songs.add("This Is What You Came For/Calvin Harris feat. Rihanna");
        songs.add("We Found Love/Rihanna feat. Calvin Harris");
        songs.add("Diamonds/Rihanna");
        songs.add("Stay/Rihanna feat. Mikky Ekko");
        songs.add("Work/Rihanna feat. Drake");
        songs.add("Love The Way You Lie/Eminem feat. Rihanna");
        songs.add("Not Afraid/Eminem");
        songs.add("Stan/Eminem feat. Dido");
        songs.add("Rap God/Eminem");
        songs.add("Till I Collapse/Eminem");
        songs.add("Without Me/Eminem");
        songs.add("Cleanin' Out My Closet/Eminem");
        songs.add("Mockingbird/Eminem");
        songs.add("Lose Yourself/Eminem");
        songs.add("The Real Slim Shady/Eminem");
        songs.add("Thrift Shop/Macklemore & Ryan Lewis feat. Wanz");
        songs.add("Can't Hold Us/Macklemore & Ryan Lewis feat. Ray Dalton");
        songs.add("Gangnam Style/PSY");
        songs.add("Waka Waka/Shakira");
        songs.add("Hips Don't Lie/Shakira feat. Wyclef Jean");
        songs.add("Whenever, Wherever/Shakira");
        songs.add("Livin' La Vida Loca/Ricky Martin");
        songs.add("Despacito/Luis Fonsi & Daddy Yankee");
        songs.add("Shape of You/Ed Sheeran");
        songs.add("Perfect/Ed Sheeran");
        songs.add("Castle on the Hill/Ed Sheeran");
        songs.add("Photograph/Ed Sheeran");
        songs.add("Thinking Out Loud/Ed Sheeran");
        songs.add("Uptown Funk/Mark Ronson feat. Bruno Mars");
        songs.add("24K Magic/Bruno Mars");
        songs.add("That's What I Like/Bruno Mars");
        songs.add("Locked Out of Heaven/Bruno Mars");
        songs.add("Just The Way You Are/Bruno Mars");
        songs.add("Grenade/Bruno Mars");
        songs.add("The Lazy Song/Bruno Mars");
        songs.add("When I Was Your Man/Bruno Mars");
        songs.add("Radioactive/Imagine Dragons");
        songs.add("Demons/Imagine Dragons");
        songs.add("Thunder/Imagine Dragons");
        songs.add("Believer/Imagine Dragons");
        songs.add("Whatever It Takes/Imagine Dragons");
        songs.add("High Hopes/Panic! At The Disco");
        songs.add("I Write Sins Not Tragedies/Panic! At The Disco");
        songs.add("Don't Stop Me Now/Queen");
        songs.add("Another One Bites the Dust/Queen");
        songs.add("We Will Rock You/Queen");
        songs.add("We Are the Champions/Queen");
        songs.add("Radio Ga Ga/Queen");
        songs.add("I Want to Break Free/Queen");
        songs.add("Killer Queen/Queen");
        songs.add("Love of My Life/Queen");
        songs.add("I Want It All/Queen");
        songs.add("Somebody to Love/Queen");
        songs.add("Who Wants to Live Forever/Queen");
        songs.add("The Show Must Go On/Queen");
        songs.add("Flash/Queen");
        songs.add("Fat Bottomed Girls/Queen");
        songs.add("Crazy Little Thing Called Love/Queen");
        songs.add("Bicycle Race/Queen");
        songs.add("Play the Game/Queen");
        songs.add("One Vision/Queen");
        songs.add("Under Pressure/Queen & David Bowie");
        songs.add("A Kind of Magic/Queen");
        songs.add("Innuendo/Queen");
        songs.add("I'm Going Slightly Mad/Queen");
        songs.add("These Are the Days of Our Lives/Queen");
        songs.add("Hammer to Fall/Queen");
        songs.add("Friends Will Be Friends/Queen");
        songs.add("The Miracle/Queen");
        songs.add("Heaven for Everyone/Queen");
        songs.add("I Was Born to Love You/Queen");
        songs.add("Let Me Live/Queen");
        songs.add("Too Much Love Will Kill You/Queen");
        songs.add("You're My Best Friend/Queen");
        songs.add("Spread Your Wings/Queen");
        songs.add("Good Old-Fashioned Lover Boy/Queen");
        songs.add("Save Me/Queen");
        songs.add("Don't Try So Hard/Queen");
        songs.add("Teo Torriatte/Queen");
        songs.add("Las Palabras De Amor/Queen");
        songs.add("Scandal/Queen");
        songs.add("The Invisible Man/Queen");
        songs.add("Breakthru/Queen");
        songs.add("Headlong/Queen");
        songs.add("It's a Hard Life/Queen");
        songs.add("Keep Yourself Alive/Queen");
        songs.add("Seven Seas of Rhye/Queen");
        songs.add("My Melancholy Blues/Queen");
        songs.add("Tie Your Mother Down/Queen");
        songs.add("No One But You/Queen");
        songs.add("Thank God It's Christmas/Queen");
        songs.add("Back Chat/Queen");
        songs.add("Body Language/Queen");
        songs.add("I'm in Love with My Car/Queen");
        songs.add("Dear Friends/Queen");
        songs.add("All Dead, All Dead/Queen");
        songs.add("Who Needs You/Queen");
        songs.add("Pain Is So Close to Pleasure/Queen");
        songs.add("One Year of Love/Queen");
        songs.add("Stone Cold Crazy/Queen");
        songs.add("'39/Queen");
        songs.add("Love of My Life (Live at Wembley)/Queen");
        songs.add("Nevermind/Nirvana");
        songs.add("In Bloom/Nirvana");
        songs.add("Lithium/Nirvana");
        songs.add("Polly/Nirvana");
        songs.add("Territorial Pissings/Nirvana");
        songs.add("Drain You/Nirvana");
        songs.add("Lounge Act/Nirvana");
        songs.add("Stay Away/Nirvana");
        songs.add("On a Plain/Nirvana");
        songs.add("Something in the Way/Nirvana");
        songs.add("Heart-Shaped Box/Nirvana");
        songs.add("All Apologies/Nirvana");
        songs.add("About a Girl/Nirvana");
        songs.add("Rape Me/Nirvana");
        songs.add("Pennyroyal Tea/Nirvana");
        songs.add("Dumb/Nirvana");
        songs.add("Serve the Servants/Nirvana");
        songs.add("Scentless Apprentice/Nirvana");
        songs.add("Very Ape/Nirvana");
        songs.add("Milk It/Nirvana");
        songs.add("Breed/Nirvana");
        songs.add("Sliver/Nirvana");
        songs.add("Been a Son/Nirvana");
        songs.add("School/Nirvana");
        songs.add("Love Buzz/Nirvana");
        songs.add("Blew/Nirvana");
        songs.add("You Know You're Right/Nirvana");
        songs.add("Where Did You Sleep Last Night/Nirvana");
        songs.add("The Man Who Sold the World/Nirvana");
        songs.add("Lake of Fire/Nirvana");
        songs.add("Oh Me/Nirvana");
        songs.add("Plateau/Nirvana");
        songs.add("Jesus Doesn't Want Me for a Sunbeam/Nirvana");
        songs.add("Dazed and Confused/Led Zeppelin");
        songs.add("Whole Lotta Love/Led Zeppelin");
        songs.add("Immigrant Song/Led Zeppelin");
        songs.add("Black Dog/Led Zeppelin");
        songs.add("Rock and Roll/Led Zeppelin");
        songs.add("Kashmir/Led Zeppelin");
        songs.add("Ramble On/Led Zeppelin");
        songs.add("Communication Breakdown/Led Zeppelin");
        songs.add("Good Times Bad Times/Led Zeppelin");
        songs.add("Over the Hills and Far Away/Led Zeppelin");
        songs.add("Heartbreaker/Led Zeppelin");
        songs.add("Going to California/Led Zeppelin");
        songs.add("Babe I'm Gonna Leave You/Led Zeppelin");
        songs.add("D'yer Mak'er/Led Zeppelin");
        songs.add("When the Levee Breaks/Led Zeppelin");
        songs.add("The Ocean/Led Zeppelin");
        songs.add("Since I've Been Loving You/Led Zeppelin");
        songs.add("No Quarter/Led Zeppelin");
        songs.add("The Rain Song/Led Zeppelin");
        songs.add("Houses of the Holy/Led Zeppelin");
        songs.add("Ten Years Gone/Led Zeppelin");
        songs.add("What Is and What Should Never Be/Led Zeppelin");
        songs.add("Trampled Under Foot/Led Zeppelin");
        songs.add("Fool in the Rain/Led Zeppelin");
        songs.add("All My Love/Led Zeppelin");
        songs.add("In the Evening/Led Zeppelin");
        songs.add("Thank You/Led Zeppelin");
        songs.add("Misty Mountain Hop/Led Zeppelin");
        songs.add("Dancing Days/Led Zeppelin");
        songs.add("The Battle of Evermore/Led Zeppelin");
        songs.add("Four Sticks/Led Zeppelin");
        songs.add("Celebration Day/Led Zeppelin");
        songs.add("In My Time of Dying/Led Zeppelin");
        songs.add("Achilles Last Stand/Led Zeppelin");
        songs.add("Your Time Is Gonna Come/Led Zeppelin");
        songs.add("Black Mountain Side/Led Zeppelin");
        songs.add("Hot Dog/Led Zeppelin");
        songs.add("Bron-Y-Aur Stomp/Led Zeppelin");
        songs.add("The Lemon Song/Led Zeppelin");
        songs.add("The Song Remains the Same/Led Zeppelin");
        songs.add("Tangerine/Led Zeppelin");
        songs.add("That's the Way/Led Zeppelin");
        songs.add("Hey Hey What Can I Do/Led Zeppelin");
        songs.add("Gallows Pole/Led Zeppelin");
        songs.add("Living Loving Maid/Led Zeppelin");
        songs.add("In the Light/Led Zeppelin");
        songs.add("Down by the Seaside/Led Zeppelin");
        songs.add("Night Flight/Led Zeppelin");
        songs.add("The Rover/Led Zeppelin");
        songs.add("Out on the Tiles/Led Zeppelin");
        songs.add("Hats Off to (Roy) Harper/Led Zeppelin");
        songs.add("Custard Pie/Led Zeppelin");
        songs.add("Candy Store Rock/Led Zeppelin");
        songs.add("Royal Orleans/Led Zeppelin");
        songs.add("Tea for One/Led Zeppelin");
        songs.add("Nobody's Fault but Mine/Led Zeppelin");
        songs.add("For Your Life/Led Zeppelin");
        songs.add("Carouselambra/Led Zeppelin");
        songs.add("South Bound Saurez/Led Zeppelin");
        songs.add("I'm Gonna Crawl/Led Zeppelin");
        songs.add("Bonzo's Montreux/Led Zeppelin");
        songs.add("I Can't Quit You Baby/Led Zeppelin");
        songs.add("How Many More Times/Led Zeppelin");
        songs.add("Bring It On Home/Led Zeppelin");
        songs.add("Boogie with Stu/Led Zeppelin");
        songs.add("Black Country Woman/Led Zeppelin");
        songs.add("The Crunge/Led Zeppelin");
        songs.add("Ozone Baby/Led Zeppelin");
        songs.add("Wearing and Tearing/Led Zeppelin");
        songs.add("Poor Tom/Led Zeppelin");
        songs.add("Walter's Walk/Led Zeppelin");
        songs.add("Darlene/Led Zeppelin");
        songs.add("Bonzo's Montreux/Led Zeppelin");
        songs.add("We're Gonna Groove/Led Zeppelin");
        songs.add("Hey Baby/Led Zeppelin");
        songs.add("Traveling Riverside Blues/Led Zeppelin");
        songs.add("White Summer/Led Zeppelin");
        songs.add("Moby Dick/Led Zeppelin");
        songs.add("Sgt. Pepper's Lonely Hearts Club Band/The Beatles");
        songs.add("With a Little Help from My Friends/The Beatles");
        songs.add("Lucy in the Sky with Diamonds/The Beatles");
        songs.add("Getting Better/The Beatles");
        songs.add("Fixing a Hole/The Beatles");
        songs.add("She's Leaving Home/The Beatles");
        songs.add("Being for the Benefit of Mr. Kite!/The Beatles");
        songs.add("Within You Without You/The Beatles");
        songs.add("When I'm Sixty-Four/The Beatles");
        songs.add("Lovely Rita/The Beatles");
        songs.add("Good Morning Good Morning/The Beatles");
        songs.add("Sgt. Pepper's Lonely Hearts Club Band (Reprise)/The Beatles");
        songs.add("A Day in the Life/The Beatles");
        songs.add("Back in the U.S.S.R./The Beatles");
        songs.add("Dear Prudence/The Beatles");
        songs.add("Glass Onion/The Beatles");
        songs.add("Ob-La-Di, Ob-La-Da/The Beatles");
        songs.add("Wild Honey Pie/The Beatles");
        songs.add("The Continuing Story of Bungalow Bill/The Beatles");
        songs.add("While My Guitar Gently Weeps/The Beatles");
        songs.add("Happiness Is a Warm Gun/The Beatles");
        songs.add("Martha My Dear/The Beatles");
        songs.add("I'm So Tired/The Beatles");
        songs.add("Blackbird/The Beatles");
        songs.add("Piggies/The Beatles");
        songs.add("Rocky Raccoon/The Beatles");
        songs.add("Don't Pass Me By/The Beatles");
        songs.add("Why Don't We Do It in the Road?/The Beatles");
        songs.add("I Will/The Beatles");
        songs.add("Julia/The Beatles");
        songs.add("Birthday/The Beatles");
        songs.add("Yer Blues/The Beatles");
        songs.add("Mother Nature's Son/The Beatles");
        songs.add("Everybody's Got Something to Hide Except Me and My Monkey/The Beatles");
        songs.add("Sexy Sadie/The Beatles");
        songs.add("Helter Skelter/The Beatles");
        songs.add("Long, Long, Long/The Beatles");
        songs.add("Revolution 1/The Beatles");
        songs.add("Honey Pie/The Beatles");
        songs.add("Savoy Truffle/The Beatles");
        songs.add("Cry Baby Cry/The Beatles");
        songs.add("Revolution 9/The Beatles");
        songs.add("Good Night/The Beatles");
        songs.add("Come Together/The Beatles");
        songs.add("Something/The Beatles");
        songs.add("Maxwell's Silver Hammer/The Beatles");
        songs.add("Oh! Darling/The Beatles");
        songs.add("Octopus's Garden/The Beatles");
        songs.add("I Want You (She's So Heavy)/The Beatles");
        songs.add("Here Comes the Sun/The Beatles");
        songs.add("Because/The Beatles");
        songs.add("You Never Give Me Your Money/The Beatles");
        songs.add("Sun King/The Beatles");
        songs.add("Mean Mr. Mustard/The Beatles");
        songs.add("Polythene Pam/The Beatles");
        songs.add("She Came in Through the Bathroom Window/The Beatles");
        songs.add("Golden Slumbers/The Beatles");
        songs.add("Carry That Weight/The Beatles");
        songs.add("The End/The Beatles");
        songs.add("Her Majesty/The Beatles");
        songs.add("Love Me Do/The Beatles");
        songs.add("Please Please Me/The Beatles");
        songs.add("From Me to You/The Beatles");
        songs.add("She Loves You/The Beatles");
        songs.add("I Want to Hold Your Hand/The Beatles");
        songs.add("Can't Buy Me Love/The Beatles");
        songs.add("A Hard Day's Night/The Beatles");
        songs.add("I Feel Fine/The Beatles");
        songs.add("Eight Days a Week/The Beatles");
        songs.add("Ticket to Ride/The Beatles");
        songs.add("Help!/The Beatles");
        songs.add("Day Tripper/The Beatles");
        songs.add("We Can Work It Out/The Beatles");
        songs.add("Paperback Writer/The Beatles");
        songs.add("Yellow Submarine/The Beatles");
        songs.add("Eleanor Rigby/The Beatles");
        songs.add("Penny Lane/The Beatles");
        songs.add("All You Need Is Love/The Beatles");
        songs.add("Hello, Goodbye/The Beatles");
        songs.add("Lady Madonna/The Beatles");
        songs.add("Hey Bulldog/The Beatles");
        songs.add("Get Back/The Beatles");
        songs.add("The Ballad of John and Yoko/The Beatles");
        songs.add("Old Brown Shoe/The Beatles");
        songs.add("Across the Universe/The Beatles");
        songs.add("Let It Be/The Beatles");
        songs.add("For You Blue/The Beatles");
        songs.add("The Long and Winding Road/The Beatles");
        songs.add("Free as a Bird/The Beatles");
        songs.add("Real Love/The Beatles");
        songs.add("I Saw Her Standing There/The Beatles");
        songs.add("Twist and Shout/The Beatles");
        songs.add("Do You Want to Know a Secret/The Beatles");
        songs.add("All My Loving/The Beatles");
        songs.add("You've Got to Hide Your Love Away/The Beatles");
        songs.add("Drive My Car/The Beatles");
        songs.add("Norwegian Wood (This Bird Has Flown)/The Beatles");
        songs.add("Nowhere Man/The Beatles");
        songs.add("Michelle/The Beatles");
        songs.add("In My Life/The Beatles");
        songs.add("Girl/The Beatles");
        songs.add("Rain/The Beatles");
        songs.add("Strawberry Fields Forever/The Beatles");
        songs.add("I Am the Walrus/The Beatles");
        songs.add("The Fool on the Hill/The Beatles");
        songs.add("Magical Mystery Tour/The Beatles");
        songs.add("Blue Jay Way/The Beatles");
        songs.add("Old Brown Shoe/The Beatles");
        songs.add("Don't Let Me Down/The Beatles");
        songs.add("One After 909/The Beatles");
        songs.add("Two of Us/The Beatles");
        songs.add("Dig a Pony/The Beatles");
        songs.add("I Me Mine/The Beatles");
        songs.add("Dig It/The Beatles");
        songs.add("Maggie Mae/The Beatles");
        songs.add("I've Got a Feeling/The Beatles");
        songs.add("One/The Beatles");
        songs.add("Across the Universe/The Beatles");
        songs.add("Let It Be/The Beatles");
        songs.add("For You Blue/The Beatles");
        songs.add("The Long and Winding Road/The Beatles");
        songs.add("Another Brick in the Wall, Pt. 2/Pink Floyd");
        songs.add("Money/Pink Floyd");
        songs.add("Time/Pink Floyd");
        songs.add("Breathe/Pink Floyd");
        songs.add("Brain Damage/Pink Floyd");
        songs.add("Eclipse/Pink Floyd");
        songs.add("Hey You/Pink Floyd");
        songs.add("Mother/Pink Floyd");
        songs.add("Run Like Hell/Pink Floyd");
        songs.add("The Great Gig in the Sky/Pink Floyd");
        songs.add("Have a Cigar/Pink Floyd");
        songs.add("Welcome to the Machine/Pink Floyd");
        songs.add("Shine On You Crazy Diamond (Pts. 1-5)/Pink Floyd");
        songs.add("Shine On You Crazy Diamond (Pts. 6-9)/Pink Floyd");
        songs.add("Learning to Fly/Pink Floyd");
        songs.add("High Hopes/Pink Floyd");
        songs.add("Marooned/Pink Floyd");
        songs.add("Keep Talking/Pink Floyd");
        songs.add("Coming Back to Life/Pink Floyd");
        songs.add("Lost for Words/Pink Floyd");
        songs.add("What Do You Want from Me/Pink Floyd");
        songs.add("On the Turning Away/Pink Floyd");
        songs.add("One Slip/Pink Floyd");
        songs.add("Yet Another Movie/Pink Floyd");
        songs.add("A New Machine (Pt. 1)/Pink Floyd");
        songs.add("Terminal Frost/Pink Floyd");
        songs.add("A New Machine (Pt. 2)/Pink Floyd");
        songs.add("Sorrow/Pink Floyd");
        songs.add("The Dogs of War/Pink Floyd");
        songs.add("One of These Days/Pink Floyd");
        songs.add("Fearless/Pink Floyd");
        songs.add("Echoes/Pink Floyd");
        songs.add("San Tropez/Pink Floyd");
        songs.add("Seamus/Pink Floyd");
        songs.add("A Pillow of Winds/Pink Floyd");
        songs.add("Atom Heart Mother Suite/Pink Floyd");
        songs.add("If/Pink Floyd");
        songs.add("Summer '68/Pink Floyd");
        songs.add("Fat Old Sun/Pink Floyd");
        songs.add("Alan's Psychedelic Breakfast/Pink Floyd");
        songs.add("Several Species of Small Furry Animals Gathered Together in a Cave and Grooving with a Pict/Pink Floyd");
        songs.add("Careful with That Axe, Eugene/Pink Floyd");
        songs.add("Astronomy Domine/Pink Floyd");
        songs.add("See Emily Play/Pink Floyd");
        songs.add("Interstellar Overdrive/Pink Floyd");
        songs.add("Arnold Layne/Pink Floyd");
        songs.add("Bike/Pink Floyd");
        songs.add("Lucifer Sam/Pink Floyd");
        songs.add("Flaming/Pink Floyd");
        songs.add("The Gnome/Pink Floyd");
        songs.add("Chapter 24/Pink Floyd");
        songs.add("The Scarecrow/Pink Floyd");
        songs.add("Remember a Day/Pink Floyd");
        songs.add("Set the Controls for the Heart of the Sun/Pink Floyd");
        songs.add("Corporal Clegg/Pink Floyd");
        songs.add("A Saucerful of Secrets/Pink Floyd");
        songs.add("Let There Be More Light/Pink Floyd");
        songs.add("Jugband Blues/Pink Floyd");
        songs.add("Julia Dream/Pink Floyd");
        songs.add("Point Me at the Sky/Pink Floyd");
        songs.add("Cirrus Minor/Pink Floyd");
        songs.add("The Nile Song/Pink Floyd");
        songs.add("Crying Song/Pink Floyd");
        songs.add("Green Is the Colour/Pink Floyd");
        songs.add("Cymbaline/Pink Floyd");
        songs.add("Party Sequence/Pink Floyd");
        songs.add("Main Theme/Pink Floyd");
        songs.add("Ibiza Bar/Pink Floyd");
        songs.add("More Blues/Pink Floyd");
        songs.add("Quicksilver/Pink Floyd");
        songs.add("A Spanish Piece/Pink Floyd");
        songs.add("Dramatic Theme/Pink Floyd");
        songs.add("Childhood's End/Pink Floyd");
        songs.add("Free Four/Pink Floyd");
        songs.add("Stay/Pink Floyd");
        songs.add("Obscured by Clouds/Pink Floyd");
        songs.add("When You're In/Pink Floyd");
        songs.add("Wot's... Uh the Deal/Pink Floyd");
        songs.add("Mudmen/Pink Floyd");
        songs.add("Burning Bridges/Pink Floyd");
        songs.add("The Gold It's in The.../Pink Floyd");
        songs.add("Absolutely Curtains/Pink Floyd");
        songs.add("The Fletcher Memorial Home/Pink Floyd");
        songs.add("Southampton Dock/Pink Floyd");
        songs.add("The Gunner's Dream/Pink Floyd");
        songs.add("Paranoid Eyes/Pink Floyd");
        songs.add("Get Your Filthy Hands Off My Desert/Pink Floyd");
        songs.add("The Post War Dream/Pink Floyd");
        songs.add("Your Possible Pasts/Pink Floyd");
        songs.add("One of the Few/Pink Floyd");
        songs.add("When the Tigers Broke Free/Pink Floyd");
        songs.add("The Hero's Return/Pink Floyd");
        songs.add("The Final Cut/Pink Floyd");
        songs.add("Not Now John/Pink Floyd");
        songs.add("Two Suns in the Sunset/Pink Floyd");
        songs.add("Cluster One/Pink Floyd");
        songs.add("What Do You Want from Me/Pink Floyd");
        songs.add("Poles Apart/Pink Floyd");
        songs.add("Marooned/Pink Floyd");
        songs.add("A Great Day for Freedom/Pink Floyd");
        songs.add("Wearing the Inside Out/Pink Floyd");
        songs.add("Take It Back/Pink Floyd");
        songs.add("Coming Back to Life/Pink Floyd");
        songs.add("Keep Talking/Pink Floyd");
        songs.add("Lost for Words/Pink Floyd");
        songs.add("High Hopes/Pink Floyd");
        songs.add("Signs of Life/Pink Floyd");
        songs.add("Learning to Fly/Pink Floyd");
        songs.add("The Dogs of War/Pink Floyd");
        songs.add("One Slip/Pink Floyd");
        songs.add("On the Turning Away/Pink Floyd");
        songs.add("Yet Another Movie/Pink Floyd");
        songs.add("Round and Around/Pink Floyd");
        songs.add("A New Machine (Pt. 1)/Pink Floyd");
        songs.add("Terminal Frost/Pink Floyd");
        songs.add("A New Machine (Pt. 2)/Pink Floyd");
        songs.add("Sorrow/Pink Floyd");
        songs.add("Bring the Boys Back Home/Pink Floyd");
        songs.add("The Trial/Pink Floyd");
        songs.add("Outside the Wall/Pink Floyd");
        songs.add("In the Flesh?/Pink Floyd");
        songs.add("The Thin Ice/Pink Floyd");
        songs.add("Another Brick in the Wall, Pt. 1/Pink Floyd");
        songs.add("The Happiest Days of Our Lives/Pink Floyd");
        songs.add("Another Brick in the Wall, Pt. 3/Pink Floyd");
        songs.add("Goodbye Cruel World/Pink Floyd");
        songs.add("Is There Anybody Out There?/Pink Floyd");
        songs.add("Nobody Home/Pink Floyd");
        songs.add("Vera/Pink Floyd");
        songs.add("Young Lust/Pink Floyd");
        songs.add("One of My Turns/Pink Floyd");
        songs.add("Don't Leave Me Now/Pink Floyd");
        songs.add("Another Brick in the Wall, Pt. 3/Pink Floyd");
        songs.add("Goodbye Cruel World/Pink Floyd");
        songs.add("Is There Anybody Out There?/Pink Floyd");
        songs.add("Nobody Home/Pink Floyd");
        songs.add("Vera/Pink Floyd");
        songs.add("In the Flesh/Pink Floyd");
        songs.add("Waiting for the Worms/Pink Floyd");
        songs.add("Stop/Pink Floyd");
        songs.add("Speak to Me/Pink Floyd");
        songs.add("Breathe (In the Air)/Pink Floyd");
        songs.add("On the Run/Pink Floyd");
        songs.add("Any Colour You Like/Pink Floyd");
        songs.add("Pigs on the Wing 1/Pink Floyd");
        songs.add("Dogs/Pink Floyd");
        songs.add("Pigs (Three Different Ones)/Pink Floyd");
        songs.add("Sheep/Pink Floyd");
        songs.add("Pigs on the Wing 2/Pink Floyd");
        songs.add("It's Hard/The Who");
        songs.add("Athena/The Who");
        songs.add("It's Your Turn/The Who");
        songs.add("Cooks County/The Who");
        songs.add("It's Hard/The Who");
        songs.add("Dangerous/The Who");
        songs.add("Eminence Front/The Who");
        songs.add("I've Known No War/The Who");
        songs.add("One Life's Enough/The Who");
        songs.add("One at a Time/The Who");
        songs.add("Why Did I Fall for That/The Who");
        songs.add("A Man Is a Man/The Who");
        songs.add("Cry If You Want/The Who");
        songs.add("Pinball Wizard/The Who");
        songs.add("I'm Free/The Who");
        songs.add("Tommy, Can You Hear Me?/The Who");
        songs.add("Go to the Mirror!/The Who");
        songs.add("Fiddle About/The Who");
        songs.add("Tommy's Holiday Camp/The Who");
        songs.add("We're Not Gonna Take It/The Who");
        songs.add("Behind Blue Eyes/The Who");
        songs.add("Won't Get Fooled Again/The Who");
        songs.add("My Generation/The Who");
        songs.add("I Can't Explain/The Who");
        songs.add("The Kids Are Alright/The Who");
        songs.add("Substitute/The Who");
        songs.add("I Can See for Miles/The Who");
        songs.add("Magic Bus/The Who");
        songs.add("5:15/The Who");
        songs.add("Squeeze Box/The Who");
        songs.add("Who Are You/The Who");
        songs.add("You Better You Bet/The Who");
        songs.add("Baba O'Riley/The Who");
        songs.add("Join Together/The Who");
        songs.add("The Real Me/The Who");
        songs.add("Long Live Rock/The Who");
        songs.add("Happy Jack/The Who");
        songs.add("Pictures of Lily/The Who");
        songs.add("Boris the Spider/The Who");
        songs.add("I'm a Boy/The Who");
        songs.add("Love, Reign o'er Me/The Who");
        songs.add("Anyway, Anyhow, Anywhere/The Who");
        songs.add("Bargain/The Who");
        songs.add("The Song Is Over/The Who");
        songs.add("Going Mobile/The Who");
        songs.add("Getting in Tune/The Who");
        songs.add("Pure and Easy/The Who");
        songs.add("Relay/The Who");
        songs.add("Let's See Action/The Who");
        songs.add("Summertime Blues/The Who");
        songs.add("Heaven and Hell/The Who");
        songs.add("Young Man Blues/The Who");
        songs.add("Fortune Teller/The Who");
        songs.add("Tattoo/The Who");
        songs.add("A Quick One, While He's Away/The Who");
        songs.add("Amazing Journey/The Who");
        songs.add("Christmas/The Who");
        songs.add("Sparks/The Who");
        songs.add("The Acid Queen/The Who");
        songs.add("Do You Think It's Alright?/The Who");
        songs.add("Miracle Cure/The Who");
        songs.add("Sally Simpson/The Who");
        songs.add("Welcome/The Who");
        songs.add("Bell Boy/The Who");
        songs.add("Dr. Jimmy/The Who");
        songs.add("Sea and Sand/The Who");
        songs.add("Quadrophenia/The Who");
        songs.add("Cut My Hair/The Who");
        songs.add("The Punk and the Godfather/The Who");
        songs.add("I'm One/The Who");
        songs.add("The Dirty Jobs/The Who");
        songs.add("Helpless Dancer/The Who");
        songs.add("Is It in My Head?/The Who");
        songs.add("I've Had Enough/The Who");
        songs.add("Drowned/The Who");
        songs.add("Doctor Jimmy/The Who");
        songs.add("The Rock/The Who");
        songs.add("Love, Reign O'er Me/The Who");
        songs.add("Sunrise/The Who");
        songs.add("New Song/The Who");
        songs.add("Had Enough/The Who");
        songs.add("905/The Who");
        songs.add("Sister Disco/The Who");
        songs.add("Music Must Change/The Who");
        songs.add("Trick of the Light/The Who");
        songs.add("Guitar and Pen/The Who");
        songs.add("Love Is Coming Down/The Who");
        songs.add("Who Are You/The Who");
        songs.add("Real Good Looking Boy/The Who");
        songs.add("Old Red Wine/The Who");
        songs.add("Tea & Theatre/The Who");
        songs.add("Wire & Glass/The Who");
        songs.add("Mirror Door/The Who");
        songs.add("Man in a Purple Dress/The Who");
        songs.add("Mike Post Theme/The Who");
        songs.add("Black Widow's Eyes/The Who");
        songs.add("It's Not Enough/The Who");
        songs.add("They Made My Dream Come True/The Who");
        songs.add("Sound Round/The Who");
        songs.add("Pick Up the Peace/The Who");
        songs.add("We Got a Hit/The Who");
        songs.add("Fragments/The Who");
        songs.add("Fragments of Fragments/The Who");
        songs.add("Unholy Trinity/The Who");
        songs.add("Trilby's Piano/The Who");
        songs.add("Endless Wire/The Who");
        songs.add("A Man in a Purple Dress/The Who");
        songs.add("Mike Post Theme/The Who");
        songs.add("Black Widow's Eyes/The Who");
        songs.add("Two Thousand Years/The Who");
        songs.add("You Better You Bet/The Who");
        songs.add("It's Not True/The Who");
        songs.add("I Don't Even Know Myself/The Who");
        songs.add("Water/The Who");
        songs.add("My Wife/The Who");
        songs.add("Slip Kid/The Who");
        songs.add("However Much I Booze/The Who");
        songs.add("Dreaming from the Waist/The Who");
        songs.add("Imagine a Man/The Who");
        songs.add("Success Story/The Who");
        songs.add("They're All in Love/The Who");
        songs.add("Blue, Red and Grey/The Who");
        songs.add("How Many Friends/The Who");
        songs.add("In a Hand or a Face/The Who");

        return songs;
    }

    public static List<SongV2> getSongV2() {
        List<SongV2> songs = new ArrayList<>();
        songs.add(new SongV2("Bohemian Rhapsody", "Queen", 72));
        songs.add(new SongV2("Imagine", "John Lennon", 75));
        songs.add(new SongV2("Stairway to Heaven", "Led Zeppelin", 82));
        songs.add(new SongV2("Hotel California", "Eagles", 75));
        songs.add(new SongV2("Hey Jude", "The Beatles", 74));
        songs.add(new SongV2("Smells Like Teen Spirit", "Nirvana", 117));
        songs.add(new SongV2("Billie Jean", "Michael Jackson", 117));
        songs.add(new SongV2("Sweet Child O' Mine", "Guns N' Roses", 125));
        songs.add(new SongV2("Like a Rolling Stone", "Bob Dylan", 95));
        songs.add(new SongV2("Purple Haze", "Jimi Hendrix", 110));
        songs.add(new SongV2("Wonderwall", "Oasis", 87));
        songs.add(new SongV2("Yesterday", "The Beatles", 85));
        songs.add(new SongV2("Let It Be", "The Beatles", 72));
        songs.add(new SongV2("Comfortably Numb", "Pink Floyd", 126));
        songs.add(new SongV2("Wish You Were Here", "Pink Floyd", 60));
        songs.add(new SongV2("No Woman No Cry", "Bob Marley", 78));
        songs.add(new SongV2("Redemption Song", "Bob Marley", 82));
        songs.add(new SongV2("Dancing Queen", "ABBA", 101));
        songs.add(new SongV2("Hallelujah", "Jeff Buckley", 64));
        songs.add(new SongV2("God Only Knows", "The Beach Boys", 120));
        songs.add(new SongV2("Gimme Shelter", "The Rolling Stones", 120));
        songs.add(new SongV2("London Calling", "The Clash", 150));
        songs.add(new SongV2("Karma Police", "Radiohead", 80));
        songs.add(new SongV2("With Or Without You", "U2", 112));
        songs.add(new SongV2("One", "U2", 91));
        songs.add(new SongV2("Nothing Else Matters", "Metallica", 142));
        songs.add(new SongV2("Enter Sandman", "Metallica", 123));
        songs.add(new SongV2("November Rain", "Guns N' Roses", 76));
        songs.add(new SongV2("Lose Yourself", "Eminem", 171));
        songs.add(new SongV2("Creep", "Radiohead", 92));
        songs.add(new SongV2("Killing Me Softly", "The Fugees", 92));
        songs.add(new SongV2("Superstition", "Stevie Wonder", 100));
        songs.add(new SongV2("Dancing In The Dark", "Bruce Springsteen", 149));
        songs.add(new SongV2("Where The Streets Have No Name", "U2", 126));
        songs.add(new SongV2("Pride", "U2", 108));
        songs.add(new SongV2("Roxanne", "The Police", 134));
        songs.add(new SongV2("Every Breath You Take", "The Police", 117));
        songs.add(new SongV2("Smoke On The Water", "Deep Purple", 114));
        songs.add(new SongV2("Dream On", "Aerosmith", 76));
        songs.add(new SongV2("Back In Black", "AC/DC", 94));
        songs.add(new SongV2("Highway To Hell", "AC/DC", 116));
        songs.add(new SongV2("Livin' On A Prayer", "Bon Jovi", 123));
        songs.add(new SongV2("Don't Stop Believin'", "Journey", 118));
        songs.add(new SongV2("Sweet Caroline", "Neil Diamond", 123));
        songs.add(new SongV2("Piano Man", "Billy Joel", 72));
        songs.add(new SongV2("Take On Me", "A-ha", 169));
        songs.add(new SongV2("Careless Whisper", "George Michael", 77));
        songs.add(new SongV2("Zombie", "The Cranberries", 84));
        songs.add(new SongV2("Bitter Sweet Symphony", "The Verve", 85));
        songs.add(new SongV2("Yellow", "Coldplay", 174));
        songs.add(new SongV2("Fix You", "Coldplay", 138));
        songs.add(new SongV2("Viva La Vida", "Coldplay", 138));
        songs.add(new SongV2("Mr. Brightside", "The Killers", 148));
        songs.add(new SongV2("Californication", "Red Hot Chili Peppers", 96));
        songs.add(new SongV2("Seven Nation Army", "The White Stripes", 124));
        songs.add(new SongV2("Crazy", "Gnarls Barkley", 112));
        songs.add(new SongV2("99 Problems", "Jay-Z", 86));
        songs.add(new SongV2("Stronger", "Kanye West", 104));
        songs.add(new SongV2("Empire State of Mind", "Jay-Z feat. Alicia Keys", 88));
        songs.add(new SongV2("Toxic", "Britney Spears", 143));
        songs.add(new SongV2("Umbrella", "Rihanna", 87));
        songs.add(new SongV2("Crazy in Love", "Beyoncé feat. Jay-Z", 99));
        songs.add(new SongV2("Single Ladies", "Beyoncé", 97));
        songs.add(new SongV2("Hey Ya!", "OutKast", 160));
        songs.add(new SongV2("In Da Club", "50 Cent", 90));
        songs.add(new SongV2("Paper Planes", "M.I.A.", 86));
        songs.add(new SongV2("Rehab", "Amy Winehouse", 104));
        songs.add(new SongV2("Rolling in the Deep", "Adele", 105));
        songs.add(new SongV2("Someone Like You", "Adele", 67));
        songs.add(new SongV2("Hello", "Adele", 79));
        songs.add(new SongV2("Uptown Funk", "Mark Ronson feat. Bruno Mars", 115));
        songs.add(new SongV2("Get Lucky", "Daft Punk feat. Pharrell Williams", 116));
        songs.add(new SongV2("Happy", "Pharrell Williams", 160));
        songs.add(new SongV2("Royals", "Lorde", 85));
        songs.add(new SongV2("Shake It Off", "Taylor Swift", 160));
        songs.add(new SongV2("Blank Space", "Taylor Swift", 96));
        songs.add(new SongV2("Thinking Out Loud", "Ed Sheeran", 79));
        songs.add(new SongV2("Shape of You", "Ed Sheeran", 96));
        songs.add(new SongV2("Can't Feel My Face", "The Weeknd", 108));
        songs.add(new SongV2("Starboy", "The Weeknd feat. Daft Punk", 93));
        songs.add(new SongV2("Hotline Bling", "Drake", 135));
        songs.add(new SongV2("God's Plan", "Drake", 77));
        songs.add(new SongV2("Sicko Mode", "Travis Scott", 78));
        songs.add(new SongV2("Humble", "Kendrick Lamar", 150));
        songs.add(new SongV2("Bad Guy", "Billie Eilish", 135));
        songs.add(new SongV2("Old Town Road", "Lil Nas X", 67));
        songs.add(new SongV2("Shallow", "Lady Gaga & Bradley Cooper", 96));
        songs.add(new SongV2("Bad Romance", "Lady Gaga", 119));
        songs.add(new SongV2("Poker Face", "Lady Gaga", 120));
        songs.add(new SongV2("Just Dance", "Lady Gaga", 119));
        songs.add(new SongV2("Wrecking Ball", "Miley Cyrus", 60));
        songs.add(new SongV2("Firework", "Katy Perry", 124));
        songs.add(new SongV2("Roar", "Katy Perry", 90));
        songs.add(new SongV2("Chandelier", "Sia", 87));
        songs.add(new SongV2("Despacito", "Luis Fonsi & Daddy Yankee", 89));
        songs.add(new SongV2("Sorry", "Justin Bieber", 100));
        songs.add(new SongV2("Havana", "Camila Cabello feat. Young Thug", 105));
        songs.add(new SongV2("Closer", "The Chainsmokers feat. Halsey", 95));
        songs.add(new SongV2("We Found Love", "Rihanna feat. Calvin Harris", 128));
        songs.add(new SongV2("Diamonds", "Rihanna", 92));
        songs.add(new SongV2("Work", "Rihanna feat. Drake", 92));
        System.out.println(songs.size());
        return songs;
    }
}
